version: "3.9"

services:
  atheris_ui:
    container_name: atheris_ui
    image: atheris_ui:0.1.0
    restart: always
    environment:
      VIRTUAL_HOST: altergeist.xyz
    networks:
      - nginx_proxy
